import {MOTION_OUTFITS,motionStyle,EMOTIONS} from './animation-player.js';
import {OUTFITS,CLOTH_COLORS,TOYS,LIFE,DESKTOP_FURNITURE,growthInfo,outfitName,outfitUnlocked,buyOutfit,wearOutfit,buyToy,toyUnlocked,desktopUnlocked,desktopCondition} from './desktop-features.js';
import {HABITS} from './habits-data.js';
import {FURNITURE_COLORS,FURNITURE_FINISHES,normalizeStyle} from './furniture-style.js';
import {DESIGNS,visibleFurniture} from './current-settings.js';
export function createDesktopUI(api){
 const {state,image,iconHTML,drawPet,openSheet,closeSheet,toast,log,save,updateUI}=api;
 const $=s=>document.querySelector(s);
 function toolbar(title,description){return `<div class="desktop-toolbar"><div><b>${title}</b><p>${description}</p></div><span>${iconHTML('acorn')} ${state.coins}</span></div>`;}
 function tabs(active){const el=document.createElement('div');el.className='tabs';for(const name of ['놀이감','옷장','생활','몸짓 도감']){const b=document.createElement('button');b.textContent=name;b.className=active===name?'active':'';b.onclick=()=>name==='옷장'?wardrobe():name==='생활'?living():name==='몸짓 도감'?animationAlbum():playroom();el.append(b);}return el;}
 function wardrobe(color=state.desktop.outfits[state.species]?.color||0,collection='motion'){
  openSheet('친구의 작은 옷장','친구에게 쏙 어울리는 작은 옷');const content=$('#sheet-content');
  const native=true;content.className='wardrobe-sheet';const growth=growthInfo(state);content.innerHTML=toolbar(native?'움직이는 친구의 새 옷':'나만의 색으로 입혀요',native?'산책 조끼 · 포근한 니트 · 카페 앞치마':'동물별 케이프 · 조끼 · 스웨터, 6가지 색')+`<div class="growth-summary"><strong>${growth.name} · 성장 ${growth.points}${growth.next?' / '+growth.next:''}</strong>${growth.next?'완료한 돌봄과 놀이로 조금씩 자라요.':'차곡차곡 쌓인 돌봄으로 어른이 되었어요.'} 우리 친구의 성장과 옷차림을 계속 기억해요.</div><div class="wardrobe-colors"></div><div class="cards wardrobe-cards"></div>`;
  content.prepend(tabs('옷장'));$('.wardrobe-colors').innerHTML='<p class=desktop-note>최신 전신 의상만 사용해요. 성장 12부터 입을 수 있고, 전용 동작이 없는 상황에는 같은 옷의 대기 모습을 유지해요.</p>';
  const previews=[];
  for(const item of native?[OUTFITS[0],...MOTION_OUTFITS]:OUTFITS.filter(i=>!motionStyle(i.id))){const owned=state.desktop.wardrobeOwned.includes(item.id),open=outfitUnlocked(state,item),wear=state.desktop.outfits[state.species]||{style:'none',color:0};const selected=wear.style===item.id&&(native||item.id==='none'||wear.color===color);const card=document.createElement('article');card.className='card outfit-card'+(selected?' selected':'')+(!open?' locked':'');card.innerHTML=`<canvas width="160" height="160" aria-label="${outfitName(state.species,item.id)} 미리보기"></canvas><b>${outfitName(state.species,item.id)}</b><div class="outfit-details">${item.id==='none'?'친구의 원래 모습':native?'동물별 전신 애니메이션':CLOTH_COLORS[color][0]+' · 16종 모두 착용 가능'}<br>${owned?'우리 옷장':open?item.price+' 도토리':native&&growth.stage==='baby'?'성장 12부터 입을 수 있어요':'Lv. '+item.level+' 또는 플레이 '+item.minutes+'분'}</div><button ${!open||(!owned&&state.coins<item.price)?'disabled':''}>${selected?'입고 있어요':owned?'입혀 주기':open?'옷장에 넣기':'아직 잠겨 있어요'}</button>`;
   card.querySelector('button').onclick=()=>{if(!owned&&!buyOutfit(state,item.id))return toast('해금 조건과 도토리를 확인해 주세요.');if(!wearOutfit(state,item.id,color))return toast('조금 더 자라면 입을 수 있어요.');save();updateUI();log(outfitName(state.species,item.id)+' 의상으로 갈아입었어요.');wardrobe(color,collection);toast('우리 친구에게 쏙 어울려요!');};
   previews.push({canvas:card.querySelector('canvas'),look:{style:item.id,color,adultPreview:item.id!=='none'}});$('.wardrobe-cards').append(card);
  }
  const container=$('.wardrobe-cards');function animate(t){if(!container.isConnected)return;for(const {canvas,look} of previews){const c=canvas.getContext('2d');c.clearRect(0,0,160,160);drawPet(c,80,143,154,state.species,t/1000,false,1,null,look);}requestAnimationFrame(animate);}requestAnimationFrame(animate);
 }
 function playroom(){
  openSheet('함께 놀아요','톡 굴리고 · 찾아보고 · 함께 걸어요');const content=$('#sheet-content');content.innerHTML=toolbar('함께 놀기 '+(state.desktop.counts.play||0)+'회','완료한 놀이 또는 플레이 시간으로 새 놀이감이 열려요')+'<p class="desktop-note">공과 생쥐는 방에 놓고 톡 누르거나 손가락으로 밀어 주세요. 완료한 놀이만 보상과 성장에 반영돼요.</p><div class="cards toy-cards"></div>';content.prepend(tabs('놀이감'));
  for(const toy of TOYS){const open=toyUnlocked(state,toy),owned=['acorn','follow','rug'].includes(toy.id)||state.owned.includes(toy.id),card=document.createElement('article');card.className='card toy-card'+(!open?' locked':'');card.innerHTML=`<img class="toy-art" src="assets/${toy.image}" alt="${toy.name}"><b>${toy.name}</b><p>${toy.description}</p><small class="toy-status">${open?(owned?'함께 놀 준비 완료':toy.price+' 도토리'):'놀이 '+Math.min(state.desktop.counts.play||0,toy.plays)+'/'+toy.plays+'회 또는 '+toy.minutes+'분'}</small><button ${!open||(!owned&&state.coins<toy.price)?'disabled':''}>${!open?'아직 잠겨 있어요':owned?'같이 놀기':'놀이감 구입'}</button>`;
   card.querySelector('button').onclick=()=>{if(!open)return;if(!owned){if(!buyToy(state,toy.id))return;api.recordPurchase();save();updateUI();log(toy.name+' 놀이감을 구입했어요.');playroom();toast('놀이감을 준비했어요. 같이 놀기를 눌러 주세요.');return;}if(toy.id==='basket')return basket();closeSheet();if(toy.id==='follow')api.setFollow(true);else if(toy.id==='rug')api.care('play');else api.startToy(toy.id);};$('.toy-cards').append(card);
  }
 }
 function basket(){
  if(!api.canAct()){toast('친구가 하던 일을 마칠 때까지 기다려 주세요.');return;}
  openSheet('숨은 간식 찾기','냄새를 따라, 어느 바구니일까요?');const correct=Math.floor(Math.random()*3),content=$('#sheet-content');content.innerHTML=toolbar('세 바구니 중 간식을 찾아요','빈 바구니는 한 번씩 살펴볼 수 있어요')+'<div class="basket-choices"></div>';let done=false;
  for(let i=0;i<3;i++){const b=document.createElement('button');b.innerHTML=`<img src="assets/desktop/basket.webp" alt="">${i+1}번 바구니`;b.onclick=()=>{if(done||b.disabled)return;b.disabled=true;if(i!==correct){b.innerHTML=iconHTML('flower')+'여기는 비었어요';return;}done=true;b.innerHTML=iconHTML('feed')+'간식을 찾았어요!';for(const other of $('.basket-choices').children)other.disabled=true;const finish=document.createElement('button');finish.className='pill';finish.textContent='친구와 간식 놀이하기';finish.onclick=()=>{closeSheet();api.care('play');};content.append(finish);};$('.basket-choices').append(b);}
 }
 function living(){
  openSheet('포근한 생활 시간','놓아 둔 가구를 친구와 함께 사용해요');const content=$('#sheet-content');content.innerHTML=toolbar('친구가 좋아하는 작은 일상','독서 · 음악 · 휴식 · 단장 · 물 마시기')+'<p class="desktop-note">방의 가구를 톡 눌러도 사용할 수 있어요. 잠깐 기다리면 친구가 스스로 가구를 찾아가기도 해요.</p><div class="life-grid"></div>';content.prepend(tabs('생활'));const observe=document.createElement('button');observe.className='pill';observe.textContent='친구의 작은 몸짓 · '+(growthInfo(state).stage==='baby'?'아기의 작은 몸짓':HABITS[state.species].name);observe.onclick=()=>{closeSheet();api.beginHabit();};content.insertBefore(observe,$('.life-grid'));
  const entries=[...api.catalog.filter(i=>visibleFurniture(i,state.species)&&api.activityFor(i.id))];
  for(const item of entries){const placed=state.furniture.some(f=>f.id===item.id),activity=api.activityFor(item.id),data=LIFE[activity];if(!data)continue;const row=document.createElement('article');row.className='life-card';row.innerHTML=`<img src="assets/${item.file||item.id+'.webp'}" alt="${item.name}"><b>${item.name}</b><small>${data.name} · ${placed?'우리 집에 있어요':'먼저 가구를 배치해 주세요'}</small><button>${placed?data.name:'집 꾸미기에서 준비'}</button>`;row.querySelector('button').onclick=()=>{if(!placed){api.shop();return;}closeSheet();api.beginLife(item.id);};$('.life-grid').append(row);}
 }
 function furnitureStyle(f){
  const item=api.catalog.find(i=>i.id===f.id),style=normalizeStyle(f.style),draft={...f,style};openSheet('가구의 작은 변신','색과 질감으로 나만의 방을 꾸며요');const content=$('#sheet-content');content.innerHTML=toolbar(item.name,'색 6종 · 질감 4종, 무료로 바꿀 수 있어요')+'<div class="furniture-style-preview"><canvas width="280" height="160" aria-label="가구 색과 질감 미리보기"></canvas></div><div class="wardrobe-colors furniture-colors"></div><div class="tabs finish-tabs"></div><div class="style-actions"><button class="pill" id="cancel-style">취소</button><button class="pill" id="finish-style">꾸밈 적용</button></div>';
  function paint(){const img=image(api.furnitureFile(item,{style})),canvas=content.querySelector('canvas'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,280,160);if(!img.naturalWidth)return;const w=Math.min(250,87.5*img.naturalWidth/img.naturalHeight*(draft.scale||1)),h=w*img.naturalHeight/img.naturalWidth;ctx.drawImage(api.furnitureImage(img,f.id,style),(280-w)/2,155-h,w,h);}
  function apply(){paint();}
  const controls=document.createElement('div');controls.className='furniture-size-controls';controls.innerHTML=`<label>가구 크기 <output>${Math.round((draft.scale||1)*100)}%</output><input type="range" aria-label="가구 크기" min="60" max="160" step="1" value="${Math.round((draft.scale||1)*100)}"></label><div class="tabs"><button data-layer="front">가구 앞으로</button><button data-layer="back">가구 뒤로</button><button data-layer="reset">원래 크기</button></div>`;
  controls.querySelector('input').oninput=e=>{draft.scale=Number(e.target.value)/100;controls.querySelector('output').textContent=e.target.value+'%';apply();};
  controls.querySelector('[data-layer=reset]').onclick=()=>{draft.scale=1;controls.querySelector('input').value=100;controls.querySelector('output').textContent='100%';apply();};
  for(const direction of ['front','back'])controls.querySelector('[data-layer='+direction+']').onclick=()=>{const orders=state.furniture.map(i=>i.stackOrder||0);draft.stackOrder=direction==='front'?Math.max(...orders)+1:Math.min(...orders)-1;apply();toast(direction==='front'?'가구를 앞으로 꺼냈어요.':'가구를 뒤로 옮겼어요.');};
  content.insertBefore(controls,$('.style-actions'));
  FURNITURE_COLORS.forEach(([name,tint],n)=>{const b=document.createElement('button');b.innerHTML=`<i style="background:${tint||'#f2e5cc'}"></i>${name}`;b.setAttribute('aria-pressed',String(style.color===n));b.onclick=()=>{style.color=n;apply();for(const other of $('.furniture-colors').children)other.setAttribute('aria-pressed',String(other===b));};$('.furniture-colors').append(b);});
  FURNITURE_FINISHES.forEach((name,n)=>{const b=document.createElement('button');b.textContent=name;b.className=style.finish===n?'active':'';b.onclick=()=>{style.finish=n;apply();for(const other of $('.finish-tabs').children)other.className=other===b?'active':'';};$('.finish-tabs').append(b);});
  if(DESIGNS[f.id]){const designs=document.createElement('div');designs.className='tabs';DESIGNS[f.id].forEach((name,n)=>{const b=document.createElement('button');b.textContent=name;b.className=style.design===n?'active':'';b.onclick=()=>{style.design=n;apply();const img=image(api.furnitureFile(item,{style}));if(!img.complete)img.addEventListener('load',paint,{once:true});for(const other of designs.children)other.className=other===b?'active':'';};designs.append(b);});content.insertBefore(designs,$('.style-actions'));}
  $('#cancel-style').onclick=closeSheet;$('#finish-style').onclick=()=>{Object.assign(f,draft,{style:{...style}});api.onFurnitureStyle();save();closeSheet();toast('가구의 새 꾸밈을 적용했어요.');};const img=image(item.file||item.id+'.webp');if(img.complete)paint();else img.addEventListener('load',paint,{once:true});
 }
 function animationAlbum(selected='walk'){
  openSheet('친구의 몸짓 도감','작은 몸짓 하나에도 친구의 마음이 있어요');const content=$('#sheet-content'),look=state.desktop.outfits[state.species]||{style:'none',color:0},age=growthInfo(state).stage==='baby'?'baby':'adult',style=motionStyle(look.style),banks=style?api.animationCatalog.costumes[state.species][style]:api.animationCatalog.base[state.species][age];
  const names={'walk':'총총 걷기','idle':'가만히 쉬기','eat':'냠냠 먹기','drink':'물 마시기','struggle':'버둥버둥','dizzy':'어질어질','hold-pickup':'살짝 들어 올리기','hold-idle_entry':'가만히 안아주기','hold-carry_entry':'안고 이동하기','hold-recover':'몸 추스리기','hold-release0':'살며시 내려놓기','hold-release1':'발을 모아 내려오기','hold-release2':'사뿐 내려오기','hold-release3':'자세 잡아 내려오기','home-rest':'포근한 휴식','home-tea':'차 한 모금','home-read':'책 읽기','home-nap':'새근새근 낮잠','home-groom':'털 단장하기','home-music':'음악에 흥얼흥얼','home-play':'장난감 놀이','pet':'쓰다듬기','groom':'보송보송 씻기','sleep':'잠자기','toy':'놀이하기','rest':'느긋하게 쉬기','look':'두리번거리기','sniff':'킁킁 냄새 맡기','stretch':'기지개 켜기','carry':'안기기','jump':'폴짝 뛰기','rub':'부비부비','stumble':'앗, 발이 꼬였네','sneeze':'에취, 재채기','wave':'반갑게 손 흔들기','habit':'친구의 성격 몸짓'};
  const available=Object.keys(banks).filter(b=>b!=='emotions');
  names['silly-stumble']=names.stumble;names['silly-sneeze']=names.sneeze;
  content.innerHTML=toolbar(outfitName(state.species,look.style),'지금 입은 옷과 친구의 몸짓을 함께 봐요')+'<div class="animation-album"><div class="animation-stage"><canvas width="320" height="280" aria-label="친구의 행동 미리보기"></canvas><b id="animation-name"></b></div><div class="animation-options"></div></div><p class="desktop-note">도감의 미리보기는 돌봄 보상과 성장에 영향을 주지 않아요.</p>';content.prepend(tabs('몸짓 도감'));
  let start=performance.now();function choose(bank){selected=bank;start=performance.now();$('#animation-name').textContent=names[bank]||({surprised:'깜짝 놀람',happy:'방긋 기쁨',angry:'조금 삐짐',sleepy:'졸린 눈'})[bank];for(const b of $('.animation-options').children)b.setAttribute('aria-pressed',String(b.dataset.bank===bank));}
  for(const bank of [...available,...EMOTIONS]){const b=document.createElement('button');b.dataset.bank=bank;b.textContent=names[bank]||({surprised:'깜짝 놀람',happy:'방긋 기쁨',angry:'조금 삐짐',sleepy:'졸린 눈'})[bank];b.onclick=()=>choose(bank);$('.animation-options').append(b);}choose(selected);
  const container=$('.animation-album'),canvas=content.querySelector('canvas');function animate(ms){if(!container.isConnected)return;const c=canvas.getContext('2d'),elapsed=(ms-start)/1000,isEmotion=EMOTIONS.includes(selected),spec=banks[selected],duration=spec?.duration||api.animationCatalog.base[state.species][age][selected]?.duration||4.8;c.clearRect(0,0,320,280);const pose={bank:isEmotion?'emotions':selected,emotion:isEmotion?selected:undefined,elapsed,duration};if(selected.startsWith('hold-')||selected==='dizzy')pose.progress=(elapsed%2)/2;api.drawPet(c,160,245,246,state.species,elapsed,false,1,null,look,pose);requestAnimationFrame(animate);}requestAnimationFrame(animate);
 }
 return {wardrobe,playroom,living,furnitureStyle,animationAlbum};
}
