export const RESTAURANT_FOODS = [
  {
    "id": "dish-0-0",
    "name": "당근 수프",
    "description": "당근을 푹 익혀 부드럽게 간 따뜻한 수프.",
    "category": "정식",
    "price": 8,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "rabbit",
    "level": 1,
    "minutes": 0,
    "period": null
  },
  {
    "id": "dish-0-1",
    "name": "당근 채소밥",
    "description": "잘게 썬 당근과 채소를 넣어 지은 든든한 밥.",
    "category": "정식",
    "price": 14,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "rabbit",
    "level": 2,
    "minutes": 8,
    "period": "day"
  },
  {
    "id": "dish-0-2",
    "name": "당근 케이크",
    "description": "당근의 은은한 단맛을 담아 촉촉하게 구운 케이크.",
    "category": "간식",
    "price": 18,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "rabbit",
    "level": 3,
    "minutes": 11,
    "period": "evening"
  },
  {
    "id": "dish-0-3",
    "name": "당근 국수",
    "description": "당근과 채소를 곁들인 따뜻하고 담백한 국수.",
    "category": "정식",
    "price": 12,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "rabbit",
    "level": 2,
    "minutes": 14,
    "period": "night"
  },
  {
    "id": "dish-1-0",
    "name": "연어 토스트",
    "description": "노릇한 토스트에 연어를 올린 고소한 아침 메뉴.",
    "category": "간식",
    "price": 10,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "otter",
    "level": 2,
    "minutes": 12,
    "period": "morning"
  },
  {
    "id": "dish-1-1",
    "name": "생선 구이 덮밥",
    "description": "구운 생선을 따끈한 밥 위에 얹은 든든한 덮밥.",
    "category": "정식",
    "price": 16,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "otter",
    "level": 2,
    "minutes": 15,
    "period": "day"
  },
  {
    "id": "dish-1-2",
    "name": "생선 크로켓",
    "description": "생선살을 부드럽게 빚어 겉을 바삭하게 익힌 크로켓.",
    "category": "간식",
    "price": 20,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "otter",
    "level": 3,
    "minutes": 18,
    "period": "evening"
  },
  {
    "id": "dish-1-3",
    "name": "생선 국수",
    "description": "생선과 채소의 맛을 우린 맑고 따뜻한 국수.",
    "category": "정식",
    "price": 14,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "otter",
    "level": 2,
    "minutes": 21,
    "period": "night"
  },
  {
    "id": "dish-2-0",
    "name": "도토리 죽",
    "description": "도토리와 곡물을 천천히 끓여 낸 부드러운 죽.",
    "category": "정식",
    "price": 12,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "squirrel",
    "level": 3,
    "minutes": 19,
    "period": "morning"
  },
  {
    "id": "dish-2-1",
    "name": "도토리 밥",
    "description": "도토리의 구수한 풍미를 담아 지은 곡물밥.",
    "category": "정식",
    "price": 18,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "squirrel",
    "level": 3,
    "minutes": 22,
    "period": "day"
  },
  {
    "id": "dish-2-2",
    "name": "도토리 쿠키",
    "description": "도토리 가루를 넣어 작고 바삭하게 구운 쿠키.",
    "category": "간식",
    "price": 22,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "squirrel",
    "level": 4,
    "minutes": 25,
    "period": "evening"
  },
  {
    "id": "dish-2-3",
    "name": "도토리 국수",
    "description": "도토리의 구수함을 더한 담백한 국수.",
    "category": "정식",
    "price": 16,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "squirrel",
    "level": 3,
    "minutes": 28,
    "period": "night"
  },
  {
    "id": "dish-3-0",
    "name": "밤죽",
    "description": "알밤을 으깨 천천히 끓인 은은하게 달콤한 죽.",
    "category": "정식",
    "price": 14,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "hedgehog",
    "level": 3,
    "minutes": 26,
    "period": "morning"
  },
  {
    "id": "dish-3-1",
    "name": "알밤 밥",
    "description": "포슬포슬한 알밤을 듬뿍 넣어 지은 따뜻한 밥.",
    "category": "정식",
    "price": 20,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "hedgehog",
    "level": 3,
    "minutes": 29,
    "period": "day"
  },
  {
    "id": "dish-3-2",
    "name": "밤 케이크",
    "description": "알밤의 고소한 맛을 담아 부드럽게 구운 케이크.",
    "category": "간식",
    "price": 24,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "hedgehog",
    "level": 4,
    "minutes": 32,
    "period": "evening"
  },
  {
    "id": "dish-3-3",
    "name": "알밤 수프",
    "description": "푹 익힌 밤을 곱게 갈아 낸 포근한 수프.",
    "category": "정식",
    "price": 18,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "hedgehog",
    "level": 3,
    "minutes": 35,
    "period": "night"
  },
  {
    "id": "dish-4-0",
    "name": "허브 오믈렛",
    "description": "향긋한 허브를 넣어 폭신하게 익힌 달걀 오믈렛.",
    "category": "정식",
    "price": 16,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "raccoon",
    "level": 4,
    "minutes": 33,
    "period": "morning"
  },
  {
    "id": "dish-4-1",
    "name": "허브 파스타",
    "description": "숲의 허브 향을 곁들인 산뜻한 파스타.",
    "category": "정식",
    "price": 22,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "raccoon",
    "level": 4,
    "minutes": 36,
    "period": "day"
  },
  {
    "id": "dish-4-2",
    "name": "따뜻한 허브차",
    "description": "허브를 따뜻하게 우려 향을 천천히 즐기는 차.",
    "category": "음료",
    "price": 26,
    "hunger": 12,
    "happy": 12,
    "energy": 10,
    "favorite": "raccoon",
    "level": 5,
    "minutes": 39,
    "period": "evening"
  },
  {
    "id": "dish-4-3",
    "name": "허브 수프",
    "description": "채소와 허브를 함께 끓인 가벼운 저녁 수프.",
    "category": "정식",
    "price": 20,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "raccoon",
    "level": 4,
    "minutes": 42,
    "period": "night"
  },
  {
    "id": "dish-5-0",
    "name": "산딸기 토스트",
    "description": "새콤달콤한 산딸기를 올린 바삭한 토스트.",
    "category": "간식",
    "price": 18,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "fox",
    "level": 4,
    "minutes": 40,
    "period": "morning"
  },
  {
    "id": "dish-5-1",
    "name": "산딸기 샐러드",
    "description": "산딸기와 신선한 채소를 함께 담은 산뜻한 샐러드.",
    "category": "정식",
    "price": 24,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "fox",
    "level": 4,
    "minutes": 43,
    "period": "day"
  },
  {
    "id": "dish-5-2",
    "name": "산딸기 타르트",
    "description": "바삭한 타르트 위에 산딸기를 올린 오후 간식.",
    "category": "간식",
    "price": 28,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "fox",
    "level": 5,
    "minutes": 46,
    "period": "evening"
  },
  {
    "id": "dish-5-3",
    "name": "산딸기차",
    "description": "산딸기의 향과 새콤함을 우려 낸 따뜻한 차.",
    "category": "음료",
    "price": 22,
    "hunger": 12,
    "happy": 12,
    "energy": 10,
    "favorite": "fox",
    "level": 4,
    "minutes": 49,
    "period": "night"
  },
  {
    "id": "dish-6-0",
    "name": "꿀 토스트",
    "description": "노릇한 빵에 꿀을 곁들인 달콤한 아침 토스트.",
    "category": "간식",
    "price": 20,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "bear",
    "level": 5,
    "minutes": 47,
    "period": "morning"
  },
  {
    "id": "dish-6-1",
    "name": "꿀 채소 덮밥",
    "description": "채소에 은은한 꿀 맛을 더해 밥과 함께 담은 덮밥.",
    "category": "정식",
    "price": 26,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "bear",
    "level": 5,
    "minutes": 50,
    "period": "day"
  },
  {
    "id": "dish-6-2",
    "name": "꿀 우유",
    "description": "부드러운 우유에 꿀을 풀어 낸 포근한 음료.",
    "category": "음료",
    "price": 30,
    "hunger": 12,
    "happy": 12,
    "energy": 10,
    "favorite": "bear",
    "level": 6,
    "minutes": 53,
    "period": "evening"
  },
  {
    "id": "dish-6-3",
    "name": "꿀 생강차",
    "description": "알싸한 생강과 달콤한 꿀을 함께 우린 따뜻한 차.",
    "category": "음료",
    "price": 24,
    "hunger": 12,
    "happy": 12,
    "energy": 10,
    "favorite": "bear",
    "level": 5,
    "minutes": 56,
    "period": "night"
  },
  {
    "id": "dish-7-0",
    "name": "버섯 수프",
    "description": "버섯의 깊은 풍미를 천천히 우려 낸 수프.",
    "category": "정식",
    "price": 22,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "owl",
    "level": 5,
    "minutes": 54,
    "period": "morning"
  },
  {
    "id": "dish-7-1",
    "name": "버섯 덮밥",
    "description": "향긋하게 익힌 버섯을 따뜻한 밥에 올린 덮밥.",
    "category": "정식",
    "price": 28,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "owl",
    "level": 5,
    "minutes": 57,
    "period": "day"
  },
  {
    "id": "dish-7-2",
    "name": "버섯 키슈",
    "description": "버섯과 달걀을 넣어 노릇하고 부드럽게 구운 키슈.",
    "category": "간식",
    "price": 32,
    "hunger": 20,
    "happy": 12,
    "energy": 3,
    "favorite": "owl",
    "level": 6,
    "minutes": 60,
    "period": "evening"
  },
  {
    "id": "dish-7-3",
    "name": "버섯 우동",
    "description": "버섯 국물에 통통한 면을 담은 따뜻한 우동.",
    "category": "정식",
    "price": 26,
    "hunger": 32,
    "happy": 7,
    "energy": 3,
    "favorite": "owl",
    "level": 5,
    "minutes": 63,
    "period": "night"
  }
];
