import {CROPS,recipesForCrop,cropUnlocked,plotStatus,plantCrop,waterCrop,harvestCrop,expandGarden} from './garden.js';
export function createGardenSpace(api){
 const {state,save,toast,recordEvent,updateUI,log,iconHTML}=api;let active=false,selected='carrot';
 const space=document.querySelector('#garden-space');
 function enter(crop){if(!api.prepare())return;if(typeof crop==='string'&&CROPS.some(c=>c.id===crop)){if(cropUnlocked(state,crop))selected=crop;else toast(CROPS.find(c=>c.id===crop).name+' 씨앗은 총 수확 '+CROPS.find(c=>c.id===crop).harvests+'회에 열려요.');}api.closeSheet();active=true;document.body.classList.add('garden-view');space.hidden=false;document.querySelector('#scene-garden').setAttribute('aria-pressed','true');document.querySelector('#scene-home').setAttribute('aria-pressed','false');render();}
 function home(){active=false;space.hidden=true;document.body.classList.remove('garden-view');document.querySelector('#scene-home').setAttribute('aria-pressed','true');document.querySelector('#scene-garden').setAttribute('aria-pressed','false');api.onHome();}
 function changed(){save();updateUI();render();}
 function act(i){const status=plotStatus(state,i);
  if(status.stage==='empty'){const crop=plantCrop(state,i,selected);if(!crop)return toast('씨앗 해금 조건과 도토리를 확인해 주세요.');changed();toast(crop.name+' 씨앗을 심었어요. 물을 주세요!');}
  else if(status.stage==='thirsty'){if(!waterCrop(state,i))return;changed();toast('물을 줬어요. 햇살을 받으며 쑥쑥 자라요.');}
  else if(status.stage==='ready'){const result=harvestCrop(state,i);if(!result)return;recordEvent(state,'harvest');log(result.crop.name+' '+result.amount+'개를 수확했어요.');selected=result.crop.id;changed();toast(result.crop.name+' +3'+(result.recipes.length?' · '+result.recipes.map(r=>r.name.replace('텃밭 ','')).join(' · ')+' 해금!':''));}
  else if(status.stage==='growing')toast('조금만 기다려 주세요. 작물이 자라고 있어요.');
 }
 function render(){const g=state.garden;space.innerHTML=`<div class="yard-heading"><b>우리의 작은 텃밭</b><small>수확 ${g.harvests}회 · 요리법 ${g.recipes.length}/8</small></div><div class="yard-beds"></div><canvas class="yard-pet" width="180" height="180" aria-label="텃밭에 함께 온 우리 펫"></canvas><div class="yard-tools"><button id="yard-expand"></button><button id="yard-cook">${iconHTML('feed')} 우리 주방</button><button id="yard-recipes" class="yard-recipe-link"></button></div><div class="yard-dock"><div class="yard-seeds" aria-label="심을 씨앗 선택"></div><div class="yard-stock">${CROPS.map(c=>`<span>${c.name} <b>${g.ingredients[c.id]}</b></span>`).join('')}</div></div>`;
  for(let i=0;i<3;i++){const s=plotStatus(state,i),b=document.createElement('button');b.className='yard-bed '+s.stage;b.dataset.plot=String(i);b.disabled=s.stage==='locked';b.innerHTML=`<div class="yard-soil">${s.crop?Array.from({length:3},()=>`<img src="${s.crop.art}" alt="">`).join(''):iconHTML(s.stage==='locked'?'lock':'flower')}</div><b></b><small></small>`;b.onclick=()=>act(i);space.querySelector('.yard-beds').append(b);}
  for(const c of CROPS){const b=document.createElement('button');b.className='yard-seed';b.disabled=!cropUnlocked(state,c.id);b.setAttribute('aria-pressed',String(selected===c.id));b.setAttribute('aria-label',c.name+' 씨앗 선택');b.innerHTML=`<img src="${c.art}" alt=""><div><b>${c.name}</b><small>${b.disabled?'수확 '+c.harvests+'회':c.seed+' 도토리 · '+c.seconds/60+'분'}</small></div>`;b.onclick=()=>{selected=c.id;render();};space.querySelector('.yard-seeds').append(b);}
  const ex=space.querySelector('#yard-expand'),required=g.plotCount===1?3:8,price=g.plotCount===1?40:80;ex.innerHTML=iconHTML('move')+(g.plotCount===3?'밭 확장 완료':'밭 넓히기 · '+g.harvests+'/'+required+'회 · '+price+' 도토리');ex.disabled=g.plotCount===3||g.harvests<required||state.coins<price;ex.onclick=()=>{if(!expandGarden(state))return;changed();toast('우리 텃밭이 더 넓어졌어요!');};space.querySelector('#yard-cook').onclick=()=>api.kitchen('all');const recipeLink=space.querySelector('#yard-recipes'),crop=CROPS.find(c=>c.id===selected),recipes=recipesForCrop(selected);recipeLink.innerHTML=`<img src="${crop.art}" alt=""><span>${crop.name} 요리 ${recipes.length}종<br><small>${g.discovered.includes(selected)?'요리책 열기 →':'첫 수확으로 해금 →'}</small></span>`;recipeLink.setAttribute('aria-label',crop.name+' 요리책 열기');recipeLink.title=recipes.map(r=>r.name).join(' · ');recipeLink.onclick=()=>api.kitchen(selected);update();
 }
 function update(){if(!active)return;space.querySelectorAll('.yard-stock b').forEach((b,i)=>{b.textContent=state.garden.ingredients[CROPS[i].id];});for(const b of space.querySelectorAll('.yard-bed')){const i=Number(b.dataset.plot),s=plotStatus(state,i);b.className='yard-bed '+s.stage;const action=s.stage==='empty'?CROPS.find(c=>c.id===selected).name+' 씨앗 심기':s.stage==='thirsty'?'물 주기':s.stage==='ready'?'수확하기':s.stage==='growing'?'자라는 중':'잠긴 밭';b.querySelector('b').textContent=s.stage==='empty'?CROPS.find(c=>c.id===selected).name+' 심기':s.crop?.name||'밭을 넓혀요';b.querySelector('small').textContent=s.stage==='locked'?(i===1?'수확 3회로 확장':'수확 8회로 확장'):s.stage==='empty'?'빈 밭을 톡 눌러요':s.stage==='thirsty'?'톡 눌러 물 주기':s.stage==='ready'?'톡 눌러 수확하기':Math.floor(s.remaining/60)+'분 '+s.remaining%60+'초';b.setAttribute('aria-label',(i+1)+'번 밭 · '+action);}}
 function draw(time){if(!active)return;const canvas=space.querySelector('.yard-pet'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,180,180);api.drawPet(ctx,90,164,164,state.species,time,false,1);}
 document.querySelector('#scene-garden').onclick=enter;document.querySelector('#scene-home').onclick=home;
 return {enter,home,update,draw,get active(){return active;}};
}
