import {CROPS,GARDEN_DISHES,cropUnlocked,plotStatus,plantCrop,waterCrop,harvestCrop,expandGarden,cookGardenDish} from './garden.js';
export function createGardenUI(api){
 const {state,openSheet,save,toast,iconHTML,recordEvent,updateUI,log}=api;let selected='carrot';
 const refresh=()=>{save();updateUI();};
 function navigation(active){const tabs=document.createElement('div');tabs.className='tabs garden-tabs';for(const [label,action] of [['식당 메뉴',()=>api.restaurant()],['텃밭',garden],['우리 주방',kitchen],['우리 냉장고',()=>api.restaurant('우리 냉장고')]]){const b=document.createElement('button');b.textContent=label;b.className=label===active?'active':'';b.onclick=action;tabs.append(b);}return tabs;}
 function garden(){
  openSheet('우리의 작은 텃밭','심고 · 물 주고 · 수확해서 함께 요리해요');const content=document.querySelector('#sheet-content'),g=state.garden;
  content.className='garden-sheet';content.innerHTML=`<div class="garden-banner">${iconHTML('flower')}<div><b>작은 씨앗이 맛있는 한 끼로</b><p>수확 ${g.harvests}회 · 발견한 작물 ${g.discovered.length}/4 · 요리법 ${g.recipes.length}/8</p></div><span>${iconHTML('acorn')} ${state.coins}</span></div><div class="garden-layout"><div><div class="garden-plots"></div><p class="garden-note">씨앗을 골라 빈 밭에 심고 물을 한 번 주세요. 자라는 동안 앱을 닫아도 괜찮아요. 수확물은 시들지 않아요.</p><div class="garden-expand"></div></div><aside class="garden-seeds"><b>오늘 심을 씨앗</b></aside></div><div class="garden-pantry"></div>`;content.prepend(navigation('텃밭'));
  for(let i=0;i<3;i++){
   const status=plotStatus(state,i),card=document.createElement('article');card.className='garden-plot '+status.stage;
   card.innerHTML=`<small>${i+1}번 작은 밭</small><div class="garden-soil">${status.crop?'<img src="'+status.crop.art+'" alt="'+status.crop.name+' 작물">':iconHTML('flower')}</div><b>${status.crop?.name|| (status.stage==='locked'?'밭을 넓혀요':'씨앗을 기다려요')}</b><span class="garden-timer"></span><button></button>`;
   const button=card.querySelector('button'),timer=card.querySelector('.garden-timer');
   if(status.stage==='locked'){timer.textContent=i===1?'수확 3회 · 40 도토리':'수확 8회 · 80 도토리';button.textContent='아직 잠긴 밭';button.disabled=true;}
   else if(status.stage==='empty'){timer.textContent='선택한 씨앗: '+CROPS.find(c=>c.id===selected).name;button.textContent='씨앗 심기';button.onclick=()=>{const c=plantCrop(state,i,selected);if(!c)return toast('작물 해금 조건과 도토리를 확인해 주세요.');refresh();garden();toast(c.name+' 씨앗을 심었어요. 물을 주세요!');};}
   else{timer.dataset.plot=String(i);button.dataset.plot=String(i);button.onclick=()=>{const current=plotStatus(state,i);if(current.stage==='thirsty'){waterCrop(state,i);refresh();garden();toast('촉촉하게 물을 줬어요. 조금만 기다려요.');}else if(current.stage==='ready'){const result=harvestCrop(state,i);if(!result)return;recordEvent(state,'harvest');log(result.crop.name+' '+result.amount+'개를 수확했어요.');refresh();garden();toast(result.crop.name+' +3'+(result.recipes.length?' · 새 요리법 2개가 열렸어요!':''));}};}
   content.querySelector('.garden-plots').append(card);
  }
  for(const crop of CROPS){const open=cropUnlocked(state,crop.id),b=document.createElement('button');b.className='garden-seed';b.disabled=!open;b.setAttribute('aria-pressed',String(crop.id===selected));b.innerHTML=`<img src="${crop.art}" alt=""><div><b>${crop.name} 씨앗</b><small>${open?crop.seed+' 도토리 · '+crop.seconds/60+'분':'수확 '+crop.harvests+'회부터'}</small></div>${iconHTML(open&&crop.id===selected?'check':open?'flower':'lock')}`;b.onclick=()=>{selected=crop.id;garden();};content.querySelector('.garden-seeds').append(b);}
  if(g.plotCount<3){const required=g.plotCount===1?3:8,price=g.plotCount===1?40:80,b=document.createElement('button');b.className='pill';b.textContent='밭 넓히기 · 수확 '+g.harvests+'/'+required+'회 · '+price+' 도토리';b.disabled=g.harvests<required||state.coins<price;b.onclick=()=>{if(!expandGarden(state))return;refresh();garden();toast('씨앗을 심을 작은 밭이 늘었어요!');};content.querySelector('.garden-expand').append(b);}
  content.querySelector('.garden-pantry').innerHTML=CROPS.map(c=>`<span>${c.name} <b>${g.ingredients[c.id]}개</b></span>`).join('')+'<button class="pill" id="garden-to-kitchen">수확물로 요리하기</button>';content.querySelector('#garden-to-kitchen').onclick=kitchen;
  updateTimers();
 }
 function updateTimers(){for(const el of document.querySelectorAll('.garden-timer[data-plot]')){const index=Number(el.dataset.plot),s=plotStatus(state,index),b=el.parentElement.querySelector('button');el.textContent=s.stage==='thirsty'?'물을 주면 튼튼하게 자라요':s.stage==='ready'?'수확할 준비 완료!':Math.floor(s.remaining/60)+'분 '+s.remaining%60+'초 후 수확';b.textContent=s.stage==='thirsty'?'물 주기':s.stage==='ready'?'수확하기':'쑥쑥 자라는 중';b.disabled=s.stage==='growing';el.parentElement.className='garden-plot '+s.stage;}}
 function kitchen(){
  openSheet('우리의 작은 주방','직접 기른 재료로 마음을 담아 만들어요');const content=document.querySelector('#sheet-content');content.className='garden-sheet';content.innerHTML=`<div class="garden-banner">${iconHTML('feed')}<div><b>수확할수록 늘어나는 요리책</b><p>작물을 처음 수확하면 해당 요리법 2개가 열려요. 재료로 만든 요리는 냉장고에 보관돼요.</p></div><span>완성 ${state.garden.cooked}접시</span></div><div class="garden-pantry">${CROPS.map(c=>`<span>${c.name} <b>${state.garden.ingredients[c.id]}개</b></span>`).join('')}</div><div class="food-grid"></div>`;content.prepend(navigation('우리 주방'));
  for(const r of GARDEN_DISHES){const open=state.garden.recipes.includes(r.id),crop=CROPS.find(c=>c.id===r.crop),have=state.garden.ingredients[r.crop],card=document.createElement('article');card.className='food-card'+(open?'':' locked');card.innerHTML=`<div class="food-art"><img src="${r.icon}" alt="${r.name}"></div><b>${r.name}</b><p>${r.description}</p><div class="food-effects">${iconHTML('feed')} +${r.hunger} ${iconHTML('pet')} +${r.happy} ${iconHTML('sleep')} +${r.energy}</div><small>${open?crop.name+' '+have+'/'+r.amount+'개 · 냉장고 '+(state.food.stock[r.id]||0)+'접시':crop.name+' 첫 수확으로 요리법 해금'}</small><button ${!open||have<r.amount?'disabled':''}>${!open?'아직 잠긴 요리법':have<r.amount?'재료를 수확해 주세요':'한 접시 만들기'}</button>`;card.querySelector('button').setAttribute('aria-label',r.name+' 만들기');card.querySelector('button').onclick=()=>{const made=cookGardenDish(state,r.id);if(!made)return;recordEvent(state,'cook');log(made.name+' 한 접시를 만들었어요.');refresh();kitchen();toast('정성 가득한 '+made.name+'가 냉장고에 들어갔어요!');};content.querySelector('.food-grid').append(card);}
 }
 return {garden,kitchen,updateTimers,navigation};
}
