import {FOODS} from './food.js';
import {growthInfo} from './desktop-features.js';
import {GROUP_LABELS} from './current-settings.js';
export function createSettingsUI(api){return function settings(){
 const {state,openSheet,closeSheet,save,toast,iconHTML}=api,s=state.desktop.settings;
 openSheet('우리 집 설정','친구와 함께하는 작은 약속');const content=document.querySelector('#sheet-content');
 content.innerHTML=`<div class="settings-grid"><article class="setting-card"><b>${iconHTML('move')} 활동 공간</b><p>친구가 돌아다닐 방 바닥의 범위를 골라요.</p><div class="tabs space-options"></div></article><article class="setting-card"><b>${iconHTML('gift')} 자동 선물 배달</b><p>새 놀이감을 해금하면 우리 집에 무료로 배달해요. 직접 꺼낸 도구는 중복 배달하지 않아요.</p><label>집 전체 최대 <output>${s.autoDeliveryLimit}개</output><input aria-label="자동 선물 배달 최대 개수" type="range" min="0" max="5" step="1" value="${s.autoDeliveryLimit}"></label><small>지금까지 ${state.desktop.autoDelivered.length}개 배달 · 0개는 배달 끄기</small></article><article class="setting-card"><b>${iconHTML('sound-on')} 효과음</b><p>쓰다듬거나 선물을 받을 때 작은 소리가 나요.</p><button class="pill settings-sound">${s.sound?'켜짐':'꺼짐'}</button></article><article class="setting-card"><b><img src="assets/desktop/water.webp" alt=""> 물 마시기</b><p>수분 ${Math.round(state.stats.hydration)} / 100 · 방의 물컵을 톡 눌러요.</p><button class="pill water-cup">물컵 꺼내기</button></article></div><div class="growth-summary"><strong>친구의 성장 기록</strong><p>발견한 음식 취향: ${FOODS.find(i=>i.id===state.food.favoriteDiscoveries[state.species])?.name||'함께 먹으며 알아가는 중'}</p><div class="growth-records"></div></div><div class="growth-summary"><strong>우리 집 교감 기록</strong><div class="activity-records"></div><p>완료한 식사·독서·음악·휴식으로 가구가 해금돼요. 기존 시간 해금도 함께 사용할 수 있어요.</p></div><button class="pill settings-guide">함께 놀기 안내</button>`;
 const space=content.querySelector('.space-options');for(const [id,name] of [['floor','바닥에서 총총'],['room','넓은 바닥 탐험']]){const b=document.createElement('button');b.textContent=name;b.setAttribute('aria-pressed',String(s.activitySpace===id));b.onclick=()=>{s.activitySpace=id;api.onSpace();save();for(const other of space.children)other.setAttribute('aria-pressed',String(other===b));toast(name+'으로 바꿨어요.');};space.append(b);}
 content.querySelector('input').oninput=e=>{s.autoDeliveryLimit=Number(e.target.value);content.querySelector('output').textContent=s.autoDeliveryLimit+'개';save();};
 content.querySelector('.settings-sound').onclick=e=>{api.toggleSound();e.currentTarget.textContent=s.sound?'켜짐':'꺼짐';};
 content.querySelector('.water-cup').onclick=()=>{closeSheet();api.placeWater();};
 const records=content.querySelector('.growth-records');for(const [id,type,name] of api.species.filter(i=>i[0]===state.species)){const g=growthInfo(state,id),row=document.createElement('p');row.textContent=`${type} ${name} · ${g.name} · 성장 ${g.points}${g.next?' / '+g.next:''}`;records.append(row);}
 const counts=content.querySelector('.activity-records');for(const [id,name] of Object.entries(GROUP_LABELS)){const row=document.createElement('span');row.textContent=`${name} ${state.desktop.activityGroups[id]||0}회`;counts.append(row);}
 content.querySelector('.settings-guide').onclick=()=>{openSheet('친구와 함께 놀아요','처음 만난 친구를 위한 안내');content.innerHTML=`<div class="settings-grid"><article class="setting-card"><b>${iconHTML('pet')} 톡, 쓰다듬기</b><p>친구를 짧게 누르면 쓰다듬어요. 길게 잡아 끌면 안아 올리고, 손을 떼면 내려놓아요.</p></article><article class="setting-card"><b>${iconHTML('play')} 손가락 따라 산책</b><p>놀아주기에서 산책을 고른 다음 방 바닥을 누른 채 움직여요. 공과 생쥐도 손가락으로 밀 수 있어요.</p></article><article class="setting-card"><b>${iconHTML('decorate')} 나만의 집</b><p>기본·공유 가구를 놓거나 지금 친구의 고유 가구 6종을 골라요. 색·질감·디자인을 미리 보고 적용해요. 우리 친구만의 고유 가구로 집을 꾸며요.</p></article><article class="setting-card"><b>${iconHTML('flower')} 함께 자라요</b><p>성장 12부터 옷을 입고, 36부터 성체가 돼요. 돌봄 보상에는 8초, 식사·생활에는 45초 간격이 있어요. 몸짓 도감은 미리보기만 제공해요.</p></article></div>`;};
};}
