const fs=require('fs'),path=require('path'),sharp=require('sharp');
const root=path.resolve(__dirname,'..'),v3=process.argv.includes('--v3'),base=path.join(root,'design',v3?'all-species-v3':'all-species-v2','masters');
const allIds=['rabbit','otter','squirrel','hedgehog','raccoon','fox','bear','owl','cat','puppy','hamster','panda','red_panda','lamb','koala','penguin'];
const ids=process.argv.slice(2).filter(value=>!value.startsWith('--'));
if(!ids.length)ids.push(...allIds);
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
function rgbToLab(r,g,b){let R=r/255,G=g/255,B=b/255;R=R<=.04045?R/12.92:Math.pow((R+.055)/1.055,2.4);G=G<=.04045?G/12.92:Math.pow((G+.055)/1.055,2.4);B=B<=.04045?B/12.92:Math.pow((B+.055)/1.055,2.4);let x=(R*.4124+G*.3576+B*.1805)/.95047,y=R*.2126+G*.7152+B*.0722,z=(R*.0193+G*.1192+B*.9505)/1.08883;const f=v=>v>.008856?Math.cbrt(v):7.787*v+16/116;x=f(x);y=f(y);z=f(z);return [116*y-16,500*(x-y),200*(y-z)]}
function labToRgb(L,a,b){let y=(L+16)/116,x=a/500+y,z=y-b/200;const f=v=>Math.pow(v,3)>.008856?Math.pow(v,3):(v-16/116)/7.787;x=.95047*f(x);y=f(y);z=1.08883*f(z);let R=x*3.2406-y*1.5372-z*.4986,G=-x*.9689+y*1.8758+z*.0415,B=x*.0557-y*.204+z*1.057;const g=v=>255*(v<=.0031308?12.92*v:1.055*Math.pow(Math.max(0,v),1/2.4)-.055);return [clamp(Math.round(g(R)),0,255),clamp(Math.round(g(G)),0,255),clamp(Math.round(g(B)),0,255)]}
const distance=(a,b)=>(a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2;
function isSubject(r,g,b){return Math.min(g-r,b-r)<=10}
function palette(data,w,h,count=14){const pixels=[];for(let p=0;p<w*h;p+=5){const at=p*4,r=data[at],g=data[at+1],b=data[at+2];if(isSubject(r,g,b))pixels.push(rgbToLab(r,g,b))}const centers=[pixels[Math.floor(pixels.length/2)].slice()];while(centers.length<count){let far=pixels[0],best=-1;for(const pixel of pixels){const d=Math.min(...centers.map(c=>distance(pixel,c)));if(d>best){best=d;far=pixel}}centers.push(far.slice())}let weights=[];for(let n=0;n<12;n++){const sums=centers.map(()=>[0,0,0,0]);for(const pixel of pixels){let pick=0,best=Infinity;for(let i=0;i<count;i++){const d=distance(pixel,centers[i]);if(d<best){best=d;pick=i}}for(let j=0;j<3;j++)sums[pick][j]+=pixel[j];sums[pick][3]++}weights=sums.map(s=>s[3]/pixels.length);for(let i=0;i<count;i++)if(sums[i][3])centers[i]=sums[i].slice(0,3).map(v=>v/sums[i][3])}return centers.map((lab,i)=>({lab,weight:weights[i]}))}
async function match(id){const babyFile=path.join(base,id,'baby.png'),adultFile=path.join(base,id,'adult.png');if(!fs.existsSync(babyFile)||!fs.existsSync(adultFile))return;const baby=await sharp(babyFile).ensureAlpha().raw().toBuffer({resolveWithObject:true}),adult=await sharp(adultFile).ensureAlpha().raw().toBuffer({resolveWithObject:true}),target=palette(baby.data,baby.info.width,baby.info.height),source=palette(adult.data,adult.info.width,adult.info.height);const pairs=source.map(entry=>{let choice=target[0],best=Infinity;for(const candidate of target){const d=distance(entry.lab,candidate.lab)+Math.abs(Math.log((entry.weight+.01)/(candidate.weight+.01)))*45;if(d<best){best=d;choice=candidate}}return {source:entry.lab,target:choice.lab}}),result=Buffer.from(adult.data);for(let p=0;p<adult.info.width*adult.info.height;p++){const at=p*4,r=result[at],g=result[at+1],b=result[at+2];if(!isSubject(r,g,b))continue;const lab=rgbToLab(r,g,b);let pair=pairs[0],best=Infinity;for(const candidate of pairs){const d=distance(lab,candidate.source);if(d<best){best=d;pair=candidate}}const mapped=[lab[0]+pair.target[0]-pair.source[0],lab[1]+pair.target[1]-pair.source[1],lab[2]+pair.target[2]-pair.source[2]],rgb=labToRgb(mapped[0],mapped[1],mapped[2]);result[at]=rgb[0];result[at+1]=rgb[1];result[at+2]=rgb[2]}const temp=adultFile+'.tmp.png';await sharp(result,{raw:{width:adult.info.width,height:adult.info.height,channels:4}}).png().toFile(temp);fs.renameSync(temp,adultFile);console.log('PALETTE_MATCHED '+id)}
async function main(){for(const id of ids)await match(id)}
main().catch(error=>{console.error(error);process.exit(1)});
