const fs=require('fs'),path=require('path'),crypto=require('crypto'),sharp=require('sharp');
const root=path.resolve(__dirname,'..'),allIds=['rabbit','otter','squirrel','hedgehog','raccoon','fox','bear','owl','cat','puppy','hamster','panda','red_panda','lamb','koala','penguin'],full=process.argv.includes('--full'),v3=process.argv.includes('--v3'),frameCount=v3?16:8,version=v3?'all-species-v3':'all-species-v2',actions=full?['idle','walk','pet','eat','drink','sleep','carry','jump','look','sniff','wave','groom','stretch','rub','toy','rest']:['idle','walk','pet'];
const speciesArg=process.argv.find(value=>value.startsWith('--species=')),ids=speciesArg?speciesArg.slice(10).split(','):allIds;
function folder(id){if(v3)return full?path.join(root,'assets','species-v3',id):path.join(root,'design',version,'pilot-runtime',id);return id==='rabbit'?path.join(root,'assets','rabbit-v3'):(full?path.join(root,'assets','species-v2',id):path.join(root,'design',version,'pilot-runtime',id))}
function inspect(data,w,h,left){let x0=256,y0=256,x1=-1,y1=-1,n=0,sr=0,sg=0,sb=0;const raw=Buffer.alloc(256*256*4);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const source=(y*w+left+x)*4,target=(y*256+x)*4;data.copy(raw,target,source,source+4);if(data[source+3]>24){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);if(data[source+3]>180){n++;sr+=data[source];sg+=data[source+1];sb+=data[source+2]}}}let contactPixels=0,contactSum=0;for(let y=Math.max(0,y1-7);y<=y1;y++)for(let x=0;x<256;x++){const at=(y*256+x)*4;if(raw[at+3]>90){contactPixels++;contactSum+=x}}return {hash:crypto.createHash('sha256').update(raw).digest('hex'),bound:[x0,y0,x1,y1],height:y1-y0+1,mean:n?[sr/n,sg/n,sb/n]:[0,0,0],contactPixels,contactCenter:contactPixels?contactSum/contactPixels:0}}
async function main(){const failures=[],sequences=[];for(const id of ids)for(const stage of ['baby','adult']){const byAction={};for(const action of actions){const file=path.join(folder(id),stage+'-'+action+'.png'),loaded=await sharp(file).ensureAlpha().raw().toBuffer({resolveWithObject:true});if(loaded.info.width!==frameCount*256||loaded.info.height!==256)failures.push({id,stage,action,error:'sheet-size',size:[loaded.info.width,loaded.info.height]});const frames=[];for(let i=0;i<frameCount;i++){const frame=inspect(loaded.data,loaded.info.width,loaded.info.height,i*256);frames.push(frame);if(frame.bound[2]<0)failures.push({id,stage,action,frame:i,error:'empty'});if(frame.bound[0]<=0||frame.bound[1]<=0||frame.bound[2]>=255||frame.bound[3]>=255)failures.push({id,stage,action,frame:i,error:'edge-touch',bound:frame.bound})}const unique=new Set(frames.map(x=>x.hash)).size;if(v3&&unique<12)failures.push({id,stage,action,error:'insufficient-distinct-frames',unique});byAction[action]=frames;sequences.push({id,stage,action,heights:frames.map(x=>x.height),unique})}const neutral=byAction.idle[0];for(const action of actions)if(action!=='walk')for(const index of action==='idle'?[frameCount-1]:[0,frameCount-1])if(byAction[action][index].hash!==neutral.hash)failures.push({id,stage,action,frame:index,error:'neutral-boundary-mismatch'});const neutralHeights=[neutral.height,byAction.walk[0].height,byAction.pet[0].height];if(Math.max(...neutralHeights)-Math.min(...neutralHeights)>8)failures.push({id,stage,error:'neutral-size-drift',heights:neutralHeights});const walkMean=byAction.walk[0].mean,colorDelta=Math.sqrt(walkMean.reduce((sum,v,i)=>sum+(v-neutral.mean[i])**2,0));if(colorDelta>18)failures.push({id,stage,error:'walk-color-drift',rgbDistance:Number(colorDelta.toFixed(2))});if(v3){const centers=byAction.walk.map(x=>x.contactCenter),pixels=byAction.walk.map(x=>x.contactPixels);if(Math.max(...centers)-Math.min(...centers)<2&&Math.max(...pixels)-Math.min(...pixels)<5)failures.push({id,stage,error:'walk-contact-static'})}}
 const report={generated:new Date().toISOString(),scope:ids.length+' species x 2 stages x '+actions.length+' actions x '+frameCount+' complete cels',cells:ids.length*2*actions.length*frameCount,failures,sequences};const out=full?path.join(root,'design',version,'production-review','validation.json'):path.join(root,'design',version,'pilot-review','validation.json');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2));console.log((full?'PRODUCTION_CELS=':'PILOT_CELLS=')+report.cells+' FAILURES='+failures.length);if(failures.length)console.log(JSON.stringify(failures,null,2));
}
main().catch(error=>{console.error(error);process.exit(1)});
